package v1.querier

import v1.querier.models.Subsequence

object SampleRecords {

  val records = List(DruidRecord(seriesID = "12",
    sensorID = "12",
    __time = Some("2021-05-03T11:14:59Z"),
    address = "",
    city = "",
    country = "",
    description = "",
    measure = Some(4.0),
    measure_name = "temp",
    unit ="grados",
    measure_desc = "",
    name = "sensor-temp-granada",
    region = "",
    sampling_unit = "",
    sampling_freq = 1,
    lat = "",long="",
    tags = List("we")),
  DruidRecord(seriesID = "12",
    sensorID = "12",
    __time = Some( "2021-05-03T11:15:59Z"),
    address = "",
    city = "",
    country = "",
    description = "",
    measure = Some(1.0),
    measure_name = "temp",
    unit ="grados",
    measure_desc = "",
    name = "sensor-temp-granada",
    region = "",
    sampling_unit = "",
    sampling_freq = 1,
    lat = "",long="",
    tags = List("aw")),
  DruidRecord(seriesID = "12",
    sensorID = "12",
    __time = Some("2021-05-03T11:16:59Z"),
    address = "",
    city = "",
    country = "",
    description = "",
    measure = Some(43),
    measure_name = "temp",
    unit ="grados",
    measure_desc = "",
    name = "sensor-temp-granada",
    region = "",
    sampling_unit = "",
    sampling_freq = 1,
    lat = "",long="",
    tags = List("we")),
  DruidRecord(seriesID = "13",
    sensorID = "12",
    __time = Some("2021-05-03T11:14:59Z"),
    address = "",
    city = "",
    country = "",
    description = "",
    measure = Some(4.0),
    measure_name = "temp",
    unit ="grados",
    measure_desc = "",
    name = "sensor-temp-ceuta",
    region = "",
    sampling_unit = "",
    sampling_freq = 1,
    lat = "",long="",
    tags = List("we")),
  DruidRecord(seriesID = "13",
    sensorID = "12",
    __time = Some("2021-05-03T11:15:59Z"),
    address = "",
    city = "",
    country = "",
    description = "",
    measure = Some(1.0),
    measure_name = "temp",
    unit ="grados",
    measure_desc = "",
    name = "sensor-temp-ceuta",
    region = "",
    sampling_unit = "",
    sampling_freq = 1,
    lat = "",long="",
    tags = List("aw")),
  DruidRecord(seriesID = "13",
    sensorID = "12",
    __time = Some("2021-05-03T11:16:59Z"),
    address = "",
    city = "",
    country = "",
    description = "",
    measure = Some(43),
    measure_name = "temp",
    unit ="grados",
    measure_desc = "",
    name = "sensor-temp-ceuta",
    region = "",
    sampling_unit = "",
    sampling_freq = 1,
    lat = "",long="",
    tags = List("we")))

  val subseq = List(Subsequence(2.3,1),
    Subsequence(2.1,2),
    Subsequence(2.1,3)
  )

}


