import Footer from '../app/components/Footer'
import Head from 'next/head'
import '../styles/globals.css'
import {useFields} from '../app/api/Query'
import "react-datepicker/dist/react-datepicker.css"

function MyApp({ Component, pageProps }) {
  
  const fields = useFields()
  return (
  <div className="flex-wrapper">
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
        crossOrigin="anonymous"
      />
    </Head>
      <Component {...pageProps} fields={fields} />
    <Footer />
  </div>

  )

}

export default MyApp
