openapi: 3.0.3
info:
  title: Time series analysis service
  description: Time series analysis service
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /subsequence/search:
    post:
      summary: Endpoint para hacer una busqueda por subsecuencia
      requestBody:
        description: Lista de series temporales en los que buscar la subsecuencia proporcionada
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SeriesQuery'
      responses:
        200:
          description: Respues con las distancias euclideas a la subsecuencia si todo correcto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SeriesQueryResponse'

        400:
          description: Invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryError'

components:
  schemas:
    QueryError:
      type: object
      properties:
        error:
          type: string
        errorMessage:
          type: string

    SeriesQueryResponse:
      type: array
      properties:
        type: object
        properties:
          series_id:
            type: string
          subsequences:
            items:
              type: array
              description: Subsecuencias de la serie temporal si se ha dado una subsecuencia para buscar
              items:
                type: object
                properties:
                  ed:
                    type: number
                    description: Distancia euclidea entre la subsecuencia a buscar y esta
                  start:
                    type: number
                    format: int
                    description: Principio de la subsecuencia
                  end:
                    type: number
                    format: int
                    description: Final de la subsecuencia

    Series:
      type: object
      properties:
        series_id:
          type: string
        sampling_freq:
          type: number
        sampling_unit:
          type: string
        series:
          type: array
          items:
            type: object
            properties:
              timestamp:
                type: string
                format: date-time
              measure:
                type: number
    SeriesQuery:
      type: object
      properties:
        k_nearest:
          type: number
          description: Número de subsecuencias a considerar por serie
        subsequence:
          type: object
          description: Consulta para obtener las subsecuencias más cercanas a la proporcionada
          properties:
            equality:
              type: boolean
              description: true if searching equal subsequences false otherwise
            normalization:
              type: boolean
              description: Normalización o no de la consulta. Verdadero por defecto
            series:
              type: array
              description: Subsecuencia de valores ordenados de manera que el item en la posicion 0 se corresponde con el instante 0 de la subsecuencia
              items:
                type: number
        time_series:
          type: array
          items:
            $ref:  "#/components/schemas/Series"





  
